### ISSUE TITLE
Is the example broken?

### ISSUE THREAD

**Issue by narrowtux** [pma/wabbit#7]
When I run the example program with a rabbitmq server version `3.6.9`, after about 200 messages, the connection is closed by the rabbitmq server - which in turn closes the channels and throws all kinds of errors because those channels can't be used.

Sadly I was unable to find the true cause for the disconnect because I can't seem to find where/how rabbitmq-server logs errors.

The stages will work for some time, a few events are printed and unacked messages accumulate in the rabbitmq queue.

**Comment by pma** [comment]
@narrowtux Can you share more details about your environment?

What versions of Erlang and Elixir are you using? Are you overriding any of the dependencies (amqp_client 3.6.7-pre.1, connection 1.0.4, gen_stage 0.11.0, rabbit_common 3.6.7-pre.1)?

Check https://www.rabbitmq.com/relocate.html for the location of the logs to see if you can find the reason for the disconnect.

**Comment by narrowtux** [comment]
While I'm going through that link, I've changed the versions of `amqp_client` and `rabbit_common` so they match my rabbitmq version.

I'm using Elixir 1.4.2 with Erlang/OTP 19.

**Comment by narrowtux** [comment]
I'm not actually getting errors in the log files, very weird.

The publish stage logs an error every time it tries to call `next_publish_seqno` because the process of the channel dies. This error is spammed:

```
Publish error with reason:
{:noproc,
  {:gen_server, :call, [#PID<0.187.0>, :next_publish_seqno, :infinity]}}
```

After some time, it tries to reconnect to the channel but to no avail, because the connection process is dead too:

```
15:56:37.451 [error] GenServer Sink terminating
** (stop) exited in: :gen_server.call(#PID<0.170.0>, :open_channel)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (stdlib) gen_server.erl:204: :gen_server.call/2
    (wabbit) lib/wabbit/gen_stage.ex:381: Wabbit.GenStage.open_channel/1
    (wabbit) lib/wabbit/gen_stage.ex:447: Wabbit.GenStage.open_channel_and_flush/1
    (wabbit) lib/wabbit/gen_stage.ex:293: Wabbit.GenStage.handle_info/2
    (gen_stage) lib/gen_stage.ex:2142: GenStage.noreply_callback/3
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:DOWN, #Reference<0.0.2.564>, :process, #PID<0.187.0>, :normal}
```

**Comment by narrowtux** [comment]
I'm running the example like this BTW, maybe that's an issue:

```
iex -S mix run  examples/direct_exchange.ex
```

**Comment by pma** [comment]
@narrowtux Can you start an `iex -S mix` and then paste the example to the shell (repl)?

**Comment by narrowtux** [comment]
Yeah that works without a problem.

**Comment by narrowtux** [comment]
I only wanted to run the example to evaluate if it was the right library for our app so now that it works I can use it :) Thanks for helping 👍

**Comment by pma** [comment]
@narrowtux Good to know. I'll add a `Process.sleep(:infinity)` to the bottom of the example, in case someone else runs the example this way in the future.
