### ISSUE TITLE
Cannot fetch the package

### ISSUE THREAD

**Issue by xfumihiro** [pma/wabbit#8]
mix deps.get showing error:

Failed to fetch record for 'wabbit' from registry (using cache)
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>BD44C6CD38B07E3B</RequestId><HostId>0hS58V9DocJyy3/PWLHuerf+eXHrtAbclOkIJttg1HRLDFVwLOTJQgb02ShlvLXgDlJodP+qJGg=</HostId></Error>

** (Mix) No package with name wabbit (from: mix.exs) in registry

**Comment by pma** [comment]
Hi,

This library is not yet published to hex.pm. You can still pull it as a dependency directly from Github by adding `{:wabbit, github: "pma/wabbit"}` to your mix.exs.

If you get to use it I'll appreciate any feedback. Eventually I plan to put in the extra effort to add it to hex.pm.
